framework:
<<<<<<< HEAD
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
=======
    default_locale: es
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - es
>>>>>>> bdb5781b5a582184f2ecfd0beb0743e0837c9b9a
