name: app

type: php:7.4

relationships:
    database: "mydatabase:mysql"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        

build:
    flavor: none

mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads }
    "/public/imgPerfil": { source: local, source_path: imgPerfil }


web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

        '/uploads':
            root: 'public/uploads'
            scripts: true
            allow: true
        
        '/imgPerfil':
            root: 'public/imgPerfil'
            scripts: true
            allow: true
        

disk: 1024
size: XL

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
