# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#mydatabase:
    # supported versions: 10.0, 10.1, 10.2, 10.3, 10.4
    # 5.5 is also available but not maintained upstream
        #type: mysql:10.2
        #disk: 1024
mysqldb:
        type: mysql:10.2
        disk: 2048
        configuration:
            schemas:
                - clontube
            endpoints:
                mysql:
                    default_schema: clontube
                    privileges:
                        main: admin

parameters:
    videosYMiniaturas: '%kernel.project_dir%/public/uploads/'
    imagenesPerfil: '%kernel.project_dir%/public/imgPerfil/'
services:
    # default configuration for services in *this* file
    
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
