mysqldb:
        type: mysql:10.2
        disk: 2048
        configuration:
            schemas:
                - clontube
            endpoints:
                mysql:
                    default_schema: clontube
                    privileges:
                        main: admin